### PR TITLE
Update kubernetes.rst

### PR DESCRIPTION
**Pull request by AleMScof**
I'd add the create namespace option along with the upgrade command.

### CODE REVIEW

**Comment by ralf401** [comment]
@mgruner can you please have a look? Thank you!

**Review by mgruner — COMMENTED** [review]
@ralf401 thanks a lot. The section on kubernetes in the docs is very short, and also outdated. What do you think about replacing the content with just a link to https://github.com/zammad/zammad-helm/blob/main/zammad/README.md?

**Comment by ralf401** [comment]
> @ralf401 thanks a lot. The section on kubernetes in the docs is very short, and also outdated. What do you think about replacing the content with just a link to https://github.com/zammad/zammad-helm/blob/main/zammad/README.md?

Yes sounds like a good idea if the content is outdated anyway. Another approach would be to port the content from your link to the RTD documentation. What do you think about that?

**Comment by mgruner** [comment]
That readme is part of the helm chart, so it is installed also on helm repo pages like https://artifacthub.io/packages/helm/zammad/zammad. Therefore I'd prefer to maintain the content there.

**Comment by ralf401** [comment]
@AleMScof as discussed we remove the content of this page because it is outdated. So I close your PR.

Anyway, thanks a lot for your contribution!

**Pull request closed without merging**
