### PR TITLE
Add Debug section for migration from OTRS

### PR DESCRIPTION
**Pull request by HristoA**
Hi.
Based on approved PR https://github.com/zammad/zammad/pull/3252 i made this changes also.
Please @MrGeneration  take a look and give me guideline what to modify if needed :) 
Thanks

### CODE REVIEW

**Comment by MrGeneration** [comment]
Just as follow up.
I'm currently re-working parts of this documentation which also affects the OTRS migration.

Right now your PR does not entirely fit and I'm unsure on how to integrate it in a useful way.
Would you be okay with me closing this PR after adapting your textual parts (with giving credits and all that) or would you prefer to point your pull request to the actual temporary branch of mine?

**Comment by MrGeneration** [comment]
This PR is being deprecated by https://github.com/zammad/zammad-documentation/pull/156
It does not reflect or contain the suggestions from this PR because I'm still missing feedback.

**Comment by HristoA** [comment]
Hi @MrGeneration 
Ya i am available to assist with this. Please guide me how.
Thanks

**Comment by HristoA** [comment]
Hi.
I will suggest to give me tips how to update this PR because i think to add also more info regarding https://github.com/zammad/zammad/issues/3379 
Thanks

**Comment by MrGeneration** [comment]
As the PR is currently undergoing QA it may not be a good idea to further push information into it.
It will complicate information, slow down the process and risk crucial information being lost or even worse not being verified.

I'd like to suggest to wait for #156 merge.

**Comment by MrGeneration** [comment]
Thank you for your patience!
Said pull request is merged, could you please rebase your branch based on master?

Just a heads up: `migration-otrs.rst` is no longer available, you'll now find it within `/migration/otrs.rst`.

Thanks!

**Pull request closed without merging**
