### PR TITLE
change MySQL / PostgreSQL in text to fit code

### PR DESCRIPTION
**Pull request by laenan8466**

### CODE REVIEW

**Comment by laenan8466** [comment]
change MySQL / PostgreSQL in text to fit code

**Comment by thorsteneckel** [comment]
Hi @laenan8466 - thanks for making the effort to comtribute <3 Sadly I have do decline the pull request since the code says **without** PostgreSQL / MySQL (as the text describes). The original is correct.

This is because of the strange `--without` bundler option we have to use 🙃 

Looking forward to see more PR coming 🤓

**Comment by laenan8466** [comment]
Oh my,
thank you for your clarification. I read that and thought I read it the other way around in the installation doc.

**Comment by thorsteneckel** [comment]
Yeah - happened to me, too. Thanks for your effort!

**Pull request closed without merging**
