### PR TITLE
Add Debian 11 apt

### PR DESCRIPTION
**Pull request by xf-**

### CODE REVIEW

**Comment by MrGeneration** [comment]
Nope, sorry.
Our packager does not support it - so doesn't our build process yet.

https://github.com/crohr/pkgr/issues/170
https://packager.io/gh/zammad/zammad/refs/stable

**Comment by xf-** [comment]
@MrGeneration the link works, the repo is available.
https://dl.packager.io/srv/zammad/zammad/stable/installer/debian/11.repo

**Comment by MrGeneration** [comment]
Just because manipulating the URL does work it doesn't mean the repo is available and working.
I don't know what happens there, but its NOT part of our build process right now.

We're not creating debian 11 packages.
So no, I will not merge your changes.

**Comment by xf-** [comment]
OK - i hope it will get a package.
THX for the quick response.

**Comment by MrGeneration** [comment]
Relevant: https://github.com/crohr/pkgr/issues/172

**Comment by martini** [comment]
@xf- just to make sure, packager.io is our provider for creating packages. We only can offer packages which packager.io is supporting.

**Pull request closed without merging**
