### PR TITLE
Maintenance: adjusted docker table and fixed typo

### PR DESCRIPTION
**Pull request by ralf401**

### CODE REVIEW

**Comment by ralf401** [comment]
Hi @mgruner,

I approved the former pull request and did now some slight changes:

* Column with adjusted, so it is the same for all tables (unfortunately, I had to force a line-break for 2 or 3 elements)
* Fixed a typo

Thanks for your review!

**Review by mgruner — APPROVED** [review]
Super nice. Please thank the original contributor!

**Comment by ralf401** [comment]
@sangramrath thank you very much for your contribution! :-)

**Comment by sangramrath** [comment]
Hello @ralf401 thanks for making the column width changes and merging this. I was a bit occupied with travel and have missed the notifications. 
I guess this does not reflect me as a contributor then?

**Pull request merged**
