### PR TITLE
Added Ubuntu 18.04 and Reset instructions

### PR DESCRIPTION
**Pull request by hanneshal**
@monotek is this update for 18.04 OK?

If so, please ping back to me. 

Thanks

### CODE REVIEW

**Comment by monotek** [comment]
Seems you removed the Ubuntu 16.04 part entirely? 
16.04 will get updates until 2021 so i'd like to keep it in the docs.

**Comment by monotek** [comment]
?

**Comment by MrGeneration** [comment]
I agree - 16.04 should stay on the documentation.

**Comment by monotek** [comment]
@hanneshal please fix

**Comment by MrGeneration** [comment]
I added 16.04 back, should be fine now. Merged.

**Pull request merged**
