### PR TITLE
Adding declaration of suse compatibility

### PR DESCRIPTION
**Pull request by MrGeneration**
packager.io currently does not support SLES15 which breaks compatibility to SUSE Enterprise 15 (and later) as well as openSUSE LEAP 15.0 (and later).

This commit will add remarks that we can only support SUSE earlier SLES 15, as fixing this is out of our scope.

### CODE REVIEW

**Comment by monotek** [comment]
I've already thougt about to completly drop suse support.
Is the old version even maintained anymore?

**Comment by MrGeneration** [comment]
Very good point.
Indeed, openSUSE LEAP 42.x is out of their lifecycle (this june).

However, SLES 12 has a LTSS cycle until 2027:
image

I'd like to keep this for now at least for historical reasons (and because SLES 12 is still in service).
But I wouldn't mind a note regarding dropped support and stuff. :-)

**Comment by monotek** [comment]
Maybe we could also try to find another packing method or service which is a bit better maintained...

**Comment by MrGeneration** [comment]
In the mean time a lot has changed on this Repo.
I'll have to start over...

**Comment by MrGeneration** [comment]
I'll be dropping this PR for now. It no longer has relevance.

**Pull request closed without merging**
