### PR TITLE
Add documentation for linking tickets

### PR DESCRIPTION
**Pull request by Nitair**
Hi everyone,

I decided to create another page for linking tickets as I was writing an integration to move from a custom ticket-system to Zammad, therefore I needed to adapt the linking of the tickets as well. After some research in the community forums like https://community.zammad.org/t/link-tickets-as-child-via-api-call/244 or https://community.zammad.org/t/linking-tickets-via-api/3839 which does not contain any answer, I have decided to go further in order to solve my problem. Maybe this documentation will help some people in similar situations.

I'm open for any feedback. 

Just another thing beforehand: At the GET part I have posted a full response (which is quite big). I was struggling if a shortened version would be better. In my opinion the more information the better to work with.

EDIT: While checking https://github.com/zammad/zammad-documentation/issues/84 it seems the full one is better (point: _add full, real outputs from the API as references._)

### CODE REVIEW

**Comment by MrGeneration** [comment]
oh wow how to not... I messed that up quite a lot.
First of all thank you for your effort and time creating this merge request!

Long code blocks by default are provided with a "more" like feature to reduce overall page length and allow users to retrieve the information if needed:

image


The rest of the merge request did look good. 
I did correct a incorrect linking in the endpoint toctree and switched from ``::`` to ``.. code-block: json`` to allow better highlighting. You can see that in commit 2a8b8f6bf7e0d401d118a8220626a59df9928173 in case it's interesting for you. :-)

---

One last thing, as it completely doesn't fit into the rest of our documentation style.
Do you think that a endpoint listing should be available on the top of the page?

It's kinda duplicate in my opinion which is why I'd like to remove it.
image

**Comment by Nitair** [comment]
Dear @MrGeneration,

thanks for your feedback 😊.

Sorry for messing up. I copied the tags article and it seems I messed up to do it correctly. I will be more careful if I do more pull requests. 

I think some sort of summary of all available endpoints is pretty useful especially if you want to search something specific without scrolling through all requests/response examples. 

It's like having a table of contents, which you wouldn't call unnecessary duplicates. 

But this is just my opinion. If you decide to not keep, you can remove that part.

**Comment by MrGeneration** [comment]
Okay let's remove it for now.
If we decide that this was a bad idea then we'll add it globally to all endpoint pages.

🙏

**Comment by MrGeneration** [comment]
Changes are available live already - endpoint removal will take about 5 minutes until live.

**Pull request merged**
