### PR TITLE
systemctl syntax

### PR DESCRIPTION
**Pull request by genxlee**
This fixes systemctl syntax at documentation.

### CODE REVIEW

**Comment by monotek** [comment]
Your changes actually break the syntax.

**Comment by randohinn** [comment]
@monotek How's that so? What @genxlee did is exactly right and is how the `service` and `systemctl`commands should be writen. `service NAME ACTION` and `systemctl ACTION NAME`. If you don't believe, read https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units and https://linux.die.net/man/8/service

**Comment by monotek** [comment]
Its already like that: 
https://docs.zammad.org/en/latest/install-debian.html

He changes it to the opposite:
https://github.com/zammad/zammad-documentation/pull/4/files#diff-20f2a73764d179784a7cf77965cfa7f9

The Centos  part needs indeed some rework. But as we only supporting Centos 7, which uses systemd, its still wrong.

**Comment by randohinn** [comment]
How about https://zammad.org/documentation/install/install-deb then?

**Comment by monotek** [comment]
Sorry. This is the old docu. 
The docu link on zammad.org will be replaces soon by https://docs.zammad.org/

**Comment by rkaldung** [comment]
@monotek check the links and ping me if I missed one

**Pull request closed without merging**
