### PR TITLE
Fixes #1103 - 'time_unit' attribute is not propagated over ticket articles API

### PR DESCRIPTION
**Pull request by fliebe92**
Adjusted some examples with the new attribute.

### CODE REVIEW

**Review by dvuckovic — APPROVED** [review]
@fliebe92 Looks good!

Just a question: this is for 6.1 only, right? There will be no backport of this "fix"?

**Comment by martini** [comment]
JFI: I already talked to @fliebe92 - I have performance concerns on this change. I need to invest time to verify this.

**Comment by fliebe92** [comment]
> @fliebe92 Looks good!
> 
> Just a question: this is for 6.1 only, right? There will be no backport of this "fix"?

Correct, it's an enhancement. But yeah, maybe we are going to remove it again, let's see...

**Comment by ralf401** [comment]
@fliebe92 can this be merged?

**Comment by fliebe92** [comment]
> @fliebe92 can this be merged?

Yeah, feel free to do so. Thanks for asking!

**Pull request merged**
