### PR TITLE
Add documentation for ui_sidebar_open_ticket_indicator_colored

### PR DESCRIPTION
**Pull request by mantas**
Adds documentation for `ui_sidebar_open_ticket_indicator_colored` setting

### CODE REVIEW

**Comment by MrGeneration** [comment]
I'm not sure about this one.
You're mentioning thresholds but keep people in the dark what those are.

That potentially raises the number of absolutely unneeded questions on that topic.

**Comment by mantas** [comment]
@MrGeneration do you have an example page how could I explain the thresholds? Just explain in plain text or some sort of table-like format?

**Comment by MrGeneration** [comment]
Not sure. It sometimes depends I can't give clear samples. If you'd give me the thresholds I could also think about it.

**Comment by mantas** [comment]
ticket zoom - warning for 2, danger for 3+

new agent ticket - warning for 1, danger for 2+

**Comment by MrGeneration** [comment]
Can those be configured? They seem terribly low for most bigger busy instances.

**Comment by martini** [comment]
IMO the numbers are ok. The usecase is to prevent double work because the customer created two tickets about the same topic (e. g. to get a credit note - this feature should prevent this).

**Comment by mantas** [comment]
> Can those be configured? They seem terribly low for most bigger busy instances.

No, they're hardcoded.

**Review by MrGeneration — APPROVED** [review]
Thanks, looking good to me. 
Please check my wording additions. If they're alright feel free to hit the merge button.

**Comment by mantas** [comment]
@MrGeneration looks great, thank you. Merging now.

**Pull request merged**
