### PR TITLE
Update ruby version to 2.6.8

### PR DESCRIPTION
**Pull request by mantas**
To be merged when 2.6.8 is merged into `stable` for 4.1.1 rolling updates

### CODE REVIEW

**Comment by MrGeneration** [comment]
Thanks - please update this PR:
https://github.com/zammad/zammad-documentation/pull/190

**Comment by mantas** [comment]
This is for 4.1.1, not 5.0. Sorry for not making it clear.

**Comment by mantas** [comment]
This is to be merged into current rolling stable today-ish

**Review by MrGeneration — APPROVED** [review]
Okay gotcha.
I changed `4.1.1` to `4.1` because this is what the current stable is at. `4.1.1` is the version that comes with the new release. This should reduce confusion. 

Merge when ever you're ready / it's merged.

**Pull request merged**
