### PR TITLE
Update docker-compose.rst

### PR DESCRIPTION
**Pull request by monotek**
reflect change of dockerport in: https://github.com/zammad/zammad-docker-compose/pull/194

### CODE REVIEW

**Comment by MrGeneration** [comment]
Sorry, but this PR is currently blocked by PR https://github.com/zammad/zammad-documentation/pull/156 and thus is subject to be lost if merged before.

**Comment by monotek** [comment]
My pr zammad/zammad-docker-compose#194 is merged.
Can't we just merge this one and you rebase your branch afterwards?

**Comment by MrGeneration** [comment]
> Can't we just merge this one and you rebase your branch afterwards?

No, because the section you're worked on has changed.

**Comment by monotek** [comment]
But this can be resolved by git?

The docs which is published now is wrong and the link to zammad in docker-compose context does not work.

**Comment by monotek** [comment]
Sorry, i don't get your point.

**Comment by MrGeneration** [comment]
Please have a look on this file 
https://github.com/zammad/zammad-documentation/pull/156/files#diff-67826247e07a03ecca57a3a6f09e5a358e6b12052f15b22c924c5cc488d339a7

Maybe you'll understand what my issue is at this point.

**Comment by monotek** [comment]
No. I dont get it.
Users which installing via docker-compose now will have a bad expeirence because the docs say zammad runs on port 80 but with the already merged https://github.com/zammad/zammad-docker-compose/pull/194 it does not, as it's on port 8080 now.

So the change of the port needs to be reflected in your pr anyway and also in the docs which are published now.

**Review by MrGeneration — APPROVED** [review]

**Comment by MrGeneration** [comment]
As the mentioned PR is currently in QA, I won't add new information to ensure that the collegue is not getting confused or the change is overseen.  Right now the new structure will not be able to reflect your changes. It's completely different.

**Comment by monotek** [comment]
Thanks for merging :)

Yes, i saw the changes. 
Shouldn't be a problem to put the infos on the right place though...

**Pull request merged**
